[tools]
go = "1.25"
rust = "stable"
node = "24"
bun = "latest"

# CLI Tools
ripgrep = "latest"
fd = "latest"
jq = "latest"
yq = "latest"
fzf = "latest"
zoxide = "latest"
zellij = "latest"
lazygit = "latest"
lazyjournal = "latest"
gum = "latest"
"github:saweima12/zjsh" = "latest"
resvg = "latest"
yazi = "latest"
